# NumPy provides a convenient and efficient way to handle the vast amount of data. NumPy is also very convenient with Matrix multiplication and data reshaping. NumPy is fast which makes it reasonable to work with a large set of data.



# Load Numpy and check version

In [4]:
import numpy as np
np.__version__

'1.21.5'

# how to create numpy array (1-D)

In [7]:
import numpy as np
a = np.array([5,6,7,6,5,4,9])    #create an Interger array
print(a)
print(a.dtype)    #dtype that returns the data type of the array
print(a.shape)    #The shape of an array is the number of elements in each dimension.

[5 6 7 6 5 4 9]
int32
(7,)


In [11]:
import numpy as np
a = np.arange(99)    #create an array with values less than 1 as in given as parameter
print(a)
print(a.dtype)    
print(a.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]
int32
(99,)


In [12]:
import numpy as np
a = np.array([0.0,1.0,2.0,3.0,4.1])     #create an floating-point array 
print(a)
print(a.dtype)    
print(a.shape)

[0.  1.  2.  3.  4.1]
float64
(5,)


In [16]:
import numpy as np
a = np.arange(5.)     #create an array with values less than 1 as in given as parameter
print(a)
print(a.dtype)    
print(a.shape)

[0. 1. 2. 3. 4.]
float64
(5,)


In [15]:
import numpy as np
a = np.array(['ab','b','c','d','e'])    #create an Unicode string array of length-1
print(a)
print(a.dtype)    
print(a.shape)  

['ab' 'b' 'c' 'd' 'e']
<U2
(5,)


In [9]:
import numpy as np
a = np.array(['cat','dog','bat','hat','net'])  #create an Unicode string array of length-3
print(a)
print(a.dtype)    
print(a.shape) 

['cat' 'dog' 'bat' 'hat' 'net']
<U3
(5,)


# how to create numpy array (2-D)

In [22]:
import numpy as np
a = np.array([[0,1,2,3,4],[5,6,7,8,9]])    #create an 2 dimentional Interger array
print(a)
print(a.dtype)
print(a.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
int32
(2, 5)


In [20]:
import numpy as np
a = np.arange(10).reshape(5,2)    #create an 2 dimentional Interger array using arange and reshape
print(a)
print(a.dtype)
print(a.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
int32
(5, 2)


In [21]:
import numpy as np
a = np.array([[0.0,1.0,2.0,3.0,4.0],[5.0,6.0,7.0,8.0,9.0]])    #create an 2 dimentional floating-point array
print(a)
print(a.dtype)
print(a.shape)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
float64
(2, 5)


In [19]:
import numpy as np
a = np.arange(10.0).reshape(2,5)    #create an 2 dimentional floating-point array using arange and reshape
print(a)
print(a.dtype)
print(a.shape)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
float64
(2, 5)


# how to create numpy array (3-D)

In [29]:
import numpy as np
a = np.array([[[0,1], [2,3]], [[4,5], [6,7]], [[8,9], [10,11]]]) #create an 3 dimentional Interger array
print(a)
print(a.dtype)
print(a.shape)


[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
int32
(3, 2, 2)


In [28]:
import numpy as np
a = np.arange(12).reshape(2,3,2)  #create an 2 dimentional Interger array using arange and reshape
print(a)
print(a.dtype)
print(a.shape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
int32
(2, 3, 2)


In [24]:
import numpy as np
a = np.array([[[0,1]],[[2,3]],[[4,5]]])
print(a)
print(a.dtype)
print(a.shape)

[[[0 1]]

 [[2 3]]

 [[4 5]]]
int32
(3, 1, 2)


In [23]:
import numpy as np
a = np.arange(6).reshape(3,1,2)
print(a)
print(a.dtype)
print(a.shape)

[[[0 1]]

 [[2 3]]

 [[4 5]]]
int32
(3, 1, 2)


# Creating Array of once

np.ones(shape, dtype=None) 

Return a new array of given shape and type, filled with ones.

The shape is an int or tuple of ints to define the size of the array. If we just specify an int variable, a one-dimensional array will be returned. For a tuple of ints, the array of given shape will be returned.
The dtype is an optional parameter with default value as a float. It’s used to specify the data type of the array, for example, int.


In [30]:
import numpy as np
a = np.ones(2)
print(a)
print(a.dtype)
print(a.shape)

[1 1]
int32
(2,)


In [34]:
import numpy as np
a = np.ones((2,2))
print(a)
print(a.dtype)
print(a.shape)

[[1. 1.]
 [1. 1.]]
float64
(2, 2)


By default it creates an Floating point array. To create and araay of different data type specify the dtype as paramenter.

In [25]:
import numpy as np
a = np.ones(4, dtype=np.int32)
print(a)
print(a.dtype)
print(a.shape)

[1 1 1 1]
int32
(4,)


In [26]:
import numpy as np
a = np.ones((4,4), dtype=np.int32)
print(a)
print(a.dtype)
print(a.shape)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
int32
(4, 4)


# Creating Array of Zeros

np.zeros(shape, dtype=none)

Return a new array of given shape and type, filled with zeros.

shape: int or tuple of ints: Shape of the new array, e.g., (2, 3) or 2. dtype: data-type, optional The desired data-type for the array, e.g., np.int8. Default is np.float64.

In [37]:
import numpy as np
a = np.zeros(5)
print(a)
print(a.dtype)
print(a.shape)

[0. 0. 0. 0. 0.]
float64
(5,)


In [38]:
import numpy as np
a = np.zeros((2,2))
print(a)
print(a.dtype)
print(a.shape)

[[0. 0.]
 [0. 0.]]
float64
(2, 2)


By default it creates an Floating point array. To create and araay of different data type specify the dtype as paramenter.

In [27]:
import numpy as np
a = np.zeros(4, dtype=np.int32)
print(a)
print(a.dtype)
print(a.shape)

[0 0 0 0]
int32
(4,)


In [28]:
import numpy as np
a = np.zeros((4,4), dtype=np.int32)
print(a)
print(a.dtype)
print(a.shape)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int32
(4, 4)


# Create an array with random numbers

random.randint(low, high=None, size=None, dtype=int)

Return random integers from low (inclusive) to high (exclusive).

Return random integers from the “discrete uniform” distribution of the specified dtype in the “half-open” interval [low, high). If high is None (the default), then results are from [0, low).

In [34]:
import numpy as np
a = np.random.randint(10,size=5)
print(a)
print(a.dtype)
print(a.shape)

[6 2 0 0 3]
int32
(5,)


In [32]:
import numpy as np
a = np.random.randint(5, 10, size=7)
print(a)
print(a.dtype)
print(a.shape)

[5 9 7 6 6 8 9]
int32
(7,)


In [43]:
import numpy as np
a = np.random.randint(5, size=(5,5))
print(a)
print(a.dtype)
print(a.shape)

[[3 4 1 1 1]
 [3 0 4 2 4]
 [1 2 2 0 0]
 [0 3 3 3 3]
 [4 4 2 1 0]]
int32
(5, 5)


In [35]:
import numpy as np
a = np.random.randint(5, 10, size=(2,3))
print(a)
print(a.dtype)
print(a.shape)

[[6 8 6]
 [9 5 8]]
int32
(2, 3)


Generate a 1 x 3 array with 3 different upper bounds

In [37]:
import numpy as np
a = np.random.randint(5, [10,20,30,40])
print(a)
print(a.dtype)
print(a.shape)

[ 7 18  5 31]
int32
(4,)


Generate a 1 by 3 array with 3 different lower bounds

In [46]:
import numpy as np
a = np.random.randint([1,3,5], 10)
print(a)
print(a.dtype)
print(a.shape)

[5 7 8]
int32
(3,)


Generate a 1 by 3 array with 3 different lower bounds and different upper bounds

In [43]:
import numpy as np
a = np.random.randint([1,3,5], [10,20,30])
print(a)
print(a.dtype)
print(a.shape)

[ 3  7 21]
int32
(3,)


In [44]:
import numpy as np
a = np.random.randint([[1,3,5],[2,4,6]], [[10,20,30],[10,20,30]])
print(a)
print(a.dtype)
print(a.shape)

[[ 3  4 27]
 [ 3  6  8]]
int32
(2, 3)


# random.randn        syntax: random.randn(d0, d1, ..., dn)

Return a sample (or samples) from the “standard normal” distribution.

Parameters: d0, d1, …, dnint, optional The dimensions of the returned array, must be non-negative. If no argument is given a single Python float is returned.

In [10]:
import numpy as np
a = np.random.randn(3,3)
print(a)
#print(a.dtype)
#print(a.shape)

[[-0.8349082  -0.84358209  1.49433131]
 [-0.83473282  0.18499763  0.2453991 ]
 [-1.57207592  1.31415189 -0.81478235]]


In [32]:
import numpy as np
a = np.random.randn(2,3)
print(a)
print(a.dtype)
print(a.shape)

[[-0.62073762  0.25899482  0.90236593]
 [ 0.90211706  1.15493395  0.87795115]]
float64
(2, 3)


In [9]:
import numpy as np
a = np.random.rand(3)
b = np.random.randn(3)
print(a)
print(b)

[0.81745442 0.90872507 0.62597273]
[-0.09085082 -0.73265099  1.50558431]


# NumPy Array Indexing

Get the first element from the following array:

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


Get the second element from the following array.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1])

Get third and fourth elements from the following array and add them.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

# Access 2-D Arrays

Access the element on the first row, second column:

In [13]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


Access the element on the 2nd row, 5th column:

In [14]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


# Access 3-D Arrays

Access the third element of the second array of the first array:

In [57]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [16]:
#Access the third element of the first array of the second array:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[1, 0, 2])

9


# Negative Indexing

Print the last element from the 2nd dim:

In [17]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


# NumPy Array Slicing

In [3]:
#1.Slicing in python means taking elements from one given index to another given index.
#2.We pass slice instead of index like this: [start:end]. The result includes the start 
   #index, but excludes the end index.
#3.We can also define the step, like this: [start:end:step].
#4.If we don't pass start its considered 0.
#5.If we don't pass end its considered length of array in that dimension.
#6.If we don't pass step its considered 1


Slice elements from index 1 to index 5 from the following array:

In [18]:
import numpy as np

arr = np.array([0,1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[1 2 3 4]


Slice elements from index 4 to the end of the array:

In [19]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


Slice elements from the beginning to index 4 (not included):

In [20]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


# Negative Slicing

Slice from the index 3 from the end to index 1 from the end:

In [32]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


Return every other element from index 1 to index 5:

In [34]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


Return every other element from the entire array:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

# Slicing 2-D Arrays

From the second element, slice elements from index 1 to index 4 (not included):

In [38]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


From both arrays, return index 2:

In [37]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

# NumPy Array Copy vs View

#The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.
#The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

# COPY

In [10]:
#Make a coimport numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)


[42  2  3  4  5]
[1 2 3 4 5]


# VIEW

In [11]:
#Make a view, change the original array, and display both arrays:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


# NumPy Array Reshaping

#Reshaping means changing the shape of an array.
#The shape of an array is the number of elements in each dimension.
#By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [69]:
#Convert the following 1-D array with 12 elements into a 2-D array.
#The outermost dimension will have 4 arrays, each with 3 elements:

import numpy as np

a1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print("Original Array:")
print(a1)
print("\nArray dimensions are 4x3")
a2 = a1.reshape(4, 3)
print(a2)
print("\nArray dimensions are 3x4")
a3 = a1.reshape(3, 4)
print(a3)



Original Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Array dimentions are 4x3
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Array dimentions are 3x4
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [1]:
#Convert the following 1-D array with 12 elements into a 3-D array.
#The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

import numpy as np

a1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print("Original Array:")
print(a1)

a2 = a1.reshape(2, 3, 2)
print("\nArray dimensions are 2x3x2")
print(a2)

a3 = a1.reshape(3, 2, 2)
print("\nArray dimensions are 3x2x2")
print(a3)

Original Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Array dimensions are 2x3x2
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

Array dimensions are 3x2x2
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


# Array Aggregation Functions

# sum()

In [3]:
#np.sum(array_name): Returns the sum of array elements (all row and columns).
import numpy as np
#a = np.array([4,6,3,8,5])     #1D array  26
#a = np.array(([4,6,3,8,5],[4,5,6,2,7]))   #2D array  
a = np.array(([4,6,3,8,5],[4,5,6,2,7],[8,3,9,1,0]))    #3D array
print(a)
print(np.sum(a))

[[4 6 3 8 5]
 [4 5 6 2 7]
 [8 3 9 1 0]]
71


In [20]:
#np.sum(array_name, axis=0 or 1): Returns the sum of array elements over a given axis.
import numpy as np
a = np.array(([4,6,3,8,5],[4,5,6,2,7])) #2D array
#a = np.array(([4,6,3,8,5],[4,5,6,2,7],[8,3,9,1,0])) #3D array
print(a)
print(np.sum(a, axis=0))    #across the rows (column wise)
print(a)
print(np.sum(a, axis=1))    #across the columns (row wise)

[[4 6 3 8 5]
 [4 5 6 2 7]]
[ 8 11  9 10 12]
[[4 6 3 8 5]
 [4 5 6 2 7]]
[26 24]


# mean()

In [5]:
#np.mean(array_name): Computes the arithmetic mean of given array (all row and columns).
import numpy as np
#a = np.array([4,6,3,8,5])     #1D array
a = np.array(([4,6,3,8,5],[4,5,6,2,7]))   #2D array
#a = np.array(([4,6,3,8,5],[4,5,6,2,7],[8,3,9,1,0]))    #3D array
print(a)
print(np.mean(a))

[[4 6 3 8 5]
 [4 5 6 2 7]]
5.0


In [21]:
#np.mean(array_name, axis=0 or 1): Returns the arithmetic mean of given array elements over a given axis.
import numpy as np
a = np.array(([4,6,3,8,5],[4,5,6,2,7]))   #2D array
#a = np.array(([4,6,3,8,5],[4,5,6,2,7],[8,3,9,1,0])) #3D array
print(a)
print(np.mean(a, axis=0))    #across the rows
print(a)
print(np.mean(a, axis=1))    #across the columns

[[4 6 3 8 5]
 [4 5 6 2 7]]
[4.  5.5 4.5 5.  6. ]
[[4 6 3 8 5]
 [4 5 6 2 7]]
[5.2 4.8]


# np.std(): Standard Deviation

In [28]:
#np.std(array_name): Computes the standard deviation along the specified axis. (all row and columns).
import numpy as np
#a = np.array([4,6,3,8,5])     #1D array
a = np.array(([4,6,3,8,5],[4,5,6,2,7]))   #2D array
#a = np.array(([4,6,3,8,5],[4,5,6,2,7],[8,3,9,1,0]))    #3D array
print(a)
print(np.std(a))

[[4 6 3 8 5]
 [4 5 6 2 7]]
1.7320508075688772


In [23]:
#np.std(array_name, axis= 0 or 1): Computes the standard deviation along the specified axis.
import numpy as np
a = np.array(([4,6,3,8,5],[4,5,6,2,7]))   #2D array
#a = np.array(([4,6,3,8,5],[4,5,6,2,7],[8,3,9,1,0])) #3D array
print(a)
print(np.std(a, axis=0))    #across the rows
print(a)
print(np.std(a, axis=1))    #across the columns

[[4 6 3 8 5]
 [4 5 6 2 7]]
[0.  0.5 1.5 3.  1. ]
[[4 6 3 8 5]
 [4 5 6 2 7]]
[1.72046505 1.72046505]


# np.var(): variance

In [31]:
#np.var(array_name): Computes the variance along the specified axis. (all row and columns).
import numpy as np
#a = np.array([4,6,3,8,5])     #1D array
#a = np.array(([4,6,3,8,5],[4,5,6,2,7]))   #2D array
a = np.array(([4,6,3,8,5],[4,5,6,2,7],[8,3,9,1,0]))    #3D array
print(a)
print(np.var(a))

[[4 6 3 8 5]
 [4 5 6 2 7]
 [8 3 9 1 0]]
6.595555555555555


In [32]:
#np.var(array_name, axis= 0 or 1): Computes the variance along the specified axis.
import numpy as np
a = np.array(([4,6,3,8,5],[4,5,6,2,7]))   #2D array
#a = np.array(([4,6,3,8,5],[4,5,6,2,7],[8,3,9,1,0])) #3D array
print(a)
print(np.var(a, axis=0))    #across the rows
print(a)
print(np.var(a, axis=1))    #across the columns

[[4 6 3 8 5]
 [4 5 6 2 7]]
[0.   0.25 2.25 9.   1.  ]
[[4 6 3 8 5]
 [4 5 6 2 7]]
[2.96 2.96]


# np.min(): minimum

In [35]:
#np.min(array_name): Returns the indices of the minimum values along an axis.. (all row and columns).
import numpy as np
#a = np.array([4,6,3,8,5])     #1D array
a = np.array(([4,6,3,8,5],[4,5,6,2,7]))   #2D array
#a = np.array(([4,6,3,8,5],[4,5,6,2,7],[8,3,9,1,0]))    #3D array
print(a)
print(np.min(a))

[[4 6 3 8 5]
 [4 5 6 2 7]]
2


In [34]:
#np.min(array_name, axis= 0 or 1): Returns the indices of the minimum values along an axis...
import numpy as np
a = np.array(([4,6,3,8,5],[4,5,6,2,7]))   #2D array
#a = np.array(([4,6,3,8,5],[4,5,6,2,7],[8,3,9,1,0])) #3D array
print(a)
print(np.min(a, axis=0))    #across the rows
print(a)
print(np.min(a, axis=1))    #across the columns

[[4 6 3 8 5]
 [4 5 6 2 7]]
[4 5 3 2 5]
[[4 6 3 8 5]
 [4 5 6 2 7]]
[3 2]


# np.max(): maximum

In [36]:
#np.max(array_name): Returns the indices of the max values along an axis.. (all row and columns).
import numpy as np
#a = np.array([4,6,3,8,5])     #1D array
a = np.array(([4,6,3,8,5],[4,5,6,2,7]))   #2D array
#a = np.array(([4,6,3,8,5],[4,5,6,2,7],[8,3,9,1,0]))    #3D array
print(a)
print(np.max(a))

[[4 6 3 8 5]
 [4 5 6 2 7]]
8


In [37]:
#np.max(array_name, axis= 0 or 1): Returns the indices of the maximum values along an axis...
import numpy as np
a = np.array(([4,6,3,8,5],[4,5,6,2,7]))   #2D array
#a = np.array(([4,6,3,8,5],[4,5,6,2,7],[8,3,9,1,0])) #3D array
print(a)
print(np.max(a, axis=0))    #across the rows
print(a)
print(np.max(a, axis=1))    #across the columns

[[4 6 3 8 5]
 [4 5 6 2 7]]
[4 6 6 8 7]
[[4 6 3 8 5]
 [4 5 6 2 7]]
[8 7]


# Vectorized Operations

# Use Map, Filter, Reduce and Lambda Functions with NumPy

In [7]:

import numpy as np
 
arr = np.array([1, 2, 3, 4, 5])
 
def addTwo(i):
    return i+2
   
applyall = np.vectorize(addTwo)
#res = applyall(arr)
#print(res)
#print(applyall)
print(applyall(arr))

[3 4 5 6 7]


# Transpose of a matrix

In [4]:
import numpy as np
a = np.arange(12).reshape(3,4)
print("Original Matrix\n",a)
print("Transpose of a Matrix\n",a.T)


Original Matrix
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Transpose of a Matrix
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [1]:
import numpy as np
a = np.array([4,5,4,6,5,3,5,4,6,6,5,5])
a

array([4, 5, 4, 6, 5, 3, 5, 4, 6, 6, 5, 5])

In [2]:
np.unique(a)

array([3, 4, 5, 6])

In [ ]:
np.argmin(), np.argmax()

# END