# Panda Series: 
#Series is a one-dimensional labeled array capable of holding data of any type (integer, string, float, python objects, etc.). The axis labels are collectively called index.

In [6]:
import numpy as np
import pandas as pd
ser1 = pd.Series([1,2,3,4,5])
#ser1 = pd.Series([1,2,3,4,5], dtype=np.float64)
print(ser1)
ser2 = pd.Series(['a','b','c','d'])
print(ser2)

0    1
1    2
2    3
3    4
4    5
dtype: int64
0    a
1    b
2    c
3    d
dtype: object


In [8]:
import numpy as np
import pandas as pd
score = pd.Series([23,45,65,43,10,6,7,34,0,0,0])
#score = pd.Series([23,45,65,43,10,6,7,34,0,0,0],index=['Rohit','KL Rahul','Virat','Suraya','DK','Pandya','axar','Ashwin','Kumar','Singh','Sachin'])
print(score)

0     23
1     45
2     65
3     43
4     10
5      6
6      7
7     34
8      0
9      0
10     0
dtype: int64


In [10]:
import numpy as np
import pandas as pd
i = pd.Index(["KL Rahul","Rohit","Virat","Suryakumar","Panth","Hardik","Chahal","siraj","Bumraha","Shami","Harshal"])##
score = pd.Series([23,45,65,43,10,6,7,34,0,0,0], index=i)
print(score)
#print("Total",sum(score))

KL Rahul      23
Rohit         45
Virat         65
Suryakumar    43
Panth         10
Hardik         6
Chahal         7
siraj         34
Bumraha        0
Shami          0
Harshal        0
dtype: int64


another method to create series using dictionary

In [15]:
import numpy as np
import pandas as pd
score = pd.Series({"KL Rahul":23,"Rohit":45,"Virat":65,"Suryakumar":43,"Panth":10,"Hardik":6,"Chahal":7,"siraj":34,"Bumraha":0,"Shami":0,"Harshal":0})
print(score)
#print("Total",sum(score))

KL Rahul      23
Rohit         45
Virat         65
Suryakumar    43
Panth         10
Hardik         6
Chahal         7
siraj         34
Bumraha        0
Shami          0
Harshal        0
dtype: int64


# DataFrames:

In [21]:
import numpy as np
import pandas as pd
arr = np.arange(0,9).reshape(3,3)
print(arr)    #Numpy ndarray
df = pd.DataFrame(arr,index=['a','b','c'],columns=['A','B','C'])
print(df)     #Pandas data Frame

[[0 1 2]
 [3 4 5]
 [6 7 8]]
   A  B  C
a  0  1  2
b  3  4  5
c  6  7  8


In [34]:
import numpy as np
import pandas as pd
df = pd.DataFrame([[23,24,20,19],[20,24,25,21],[19,22,23,18]], index=['Rahul','Krishna','Abhinav'], columns=['OSA','Python','SE','Java'])
print(df)

         OSA  Python  SE  Java
Rahul     23      24  20    19
Krishna   20      24  25    21
Abhinav   19      22  23    18


In [2]:
import numpy as np
import pandas as pd
df = pd.DataFrame({"OSA":[23,20,19],"Python":[20,25,23,20]})   #Error:All arrays must be of the same length
#df = pd.DataFrame({"OSA":[23,20,19,20],"Python":[20,25,23,20]})
print(df)

ValueError: All arrays must be of the same length

In [9]:
import numpy as np
import pandas as pd
ser1 = pd.Series([23,20,19])
ser2 = pd.Series([20,25,23,20])
print(pd.DataFrame({"OSA":ser1,"Python":ser2}))

    OSA  Python
0  23.0      20
1  20.0      25
2  19.0      23
3   NaN      20


# Craete DataFrame containing Information about Cities.

In [7]:
import numpy as np
import pandas as pd
i = pd.Index(['Karnataka','Maharashtra','Gujarat'])
#print(i)
pop = pd.Series(['6.72','12.54','7.0'],index=i, name="Population")
#print(pop)
cap = pd.Series(['Bangalore','Mumbai','Gandhinagar'],index=i, name="Capital")
#print(cap)
#df = pd.DataFrame([pop,cap])     #Will Not Display in Proper format
#df = pd.DataFrame([pop,cap]).T   #Will Display in Proper format but columns name missing
df = pd.DataFrame({"Population":pop, "Capital":cap })
#df = pd.DataFrame([['6.72','Bangalore'],['12.54','Mumbai'],['7.0','Gandhinagar']],index=['Karnataka','Maharashtra','Gujarat'],columns=['Population','Capital'])# ctraeting DataFramw in one line
print(df)

            Population      Capital
Karnataka         6.72    Bangalore
Maharashtra      12.54       Mumbai
Gujarat            7.0  Gandhinagar


# How to ADD new Data to a Series

In [9]:
import numpy as np
import pandas as pd
#print(pop)
pop.append(pd.Series({"Madhaya Pradesh":9.9}))
#print(pop)

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_11976\780253580.py:4: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  pop.append(pd.Series({"Madhaya Pradesh":9.9}))


Karnataka           6.72
Maharashtra        12.54
Gujarat              7.0
Madhaya Pradesh      9.9
dtype: object

# How to ADD new Data to a Series

Method1

In [11]:
import numpy as np
import pandas as pd
df = pd.DataFrame([['6.72','Bangalore'],['12.54','Mumbai'],['7.0','Gandhinagar']],index=['Karnataka','Maharashtra','Gujarat'],columns=['Population','Capital'])# ctraeting DataFrame in one line
#print(df)
print(df.append(pd.DataFrame([['8.9','Channai'],['12.54','Hydrabad']],index=['Tamil Nadu','Andra Pradesh'],columns=['Population','Capital'])))


              Population      Capital
Karnataka           6.72    Bangalore
Maharashtra        12.54       Mumbai
Gujarat              7.0  Gandhinagar
Tamil Nadu           8.9      Channai
Andra Pradesh      12.54     Hydrabad


C:\Users\ADMIN\AppData\Local\Temp\ipykernel_11976\747689594.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  print(df.append(pd.DataFrame([['8.9','Channai'],['12.54','Hydrabad']],index=['Tamil Nadu','Andra Pradesh'],columns=['Population','Capital'])))


Method2:

In [27]:
import numpy as np
import pandas as pd
i = pd.Index(['Karnataka','Maharashtra','Gujarat'])
pop = pd.Series(['6.72','12.54','7.0'],index=i, name="Population")
cap = pd.Series(['Bangalore','Mumbai','Gandhinagar'],index=i, name="Capital")
df = pd.DataFrame({"Population":pop, "Capital":cap })
print(df)
print(df.append(pd.DataFrame({"Population": pd.Series({"Tamil Nadu":8.9, "Andra Pradesh":12.6}), "Capital": pd.Series({"Tamil Nadu":"Channai", "Andra Pradesh":"Hydrabad"})})))

            Population      Capital
Karnataka         6.72    Bangalore
Maharashtra      12.54       Mumbai
Gujarat            7.0  Gandhinagar
              Population      Capital
Karnataka           6.72    Bangalore
Maharashtra        12.54       Mumbai
Gujarat              7.0  Gandhinagar
Tamil Nadu           8.9      Channai
Andra Pradesh       12.6     Hydrabad


C:\Users\ADMIN\AppData\Local\Temp\ipykernel_13440\3860572821.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  print(df.append(pd.DataFrame({"Population": pd.Series({"Tamil Nadu":8.9, "Andra Pradesh":12.6}), "Capital": pd.Series({"Tamil Nadu":"Channai", "Andra Pradesh":"Hydrabad"})})))


# Concat new column to dataFrame:

In [27]:
import numpy as np
import pandas as pd
i = pd.Index(['Karnataka','Maharashtra','Gujarat'])
pop = pd.Series(['6.72','12.54','7.0'],index=i, name="Population")
cap = pd.Series(['Bangalore','Mumbai','Gandhinagar'],index=i, name="Capital")
df = pd.DataFrame({"Population":pop, "Capital":cap })
print(df)
df1 = pd.concat(
           [df, pd.DataFrame({
                                "Area": pd.Series(['2.1','3.1','5.5'],index=pop.index),
                                "CM": pd.Series(['Bomai','Shinde','xyz'],index=pop.index)
                            })
            ], axis=1
         )
df1.to_csv("cities.csv")
df1

            Population      Capital
Karnataka         6.72    Bangalore
Maharashtra      12.54       Mumbai
Gujarat            7.0  Gandhinagar


Population      Capital Area      CM
Karnataka         6.72    Bangalore  2.1   Bomai
Maharashtra      12.54       Mumbai  3.1  Shinde
Gujarat            7.0  Gandhinagar  5.5     xyz