# NUMPY LIBRARY

In [1]:
import numpy as np
np.__version__

'1.21.5'

# CREATE A 1-D ARRAY USING array()

In [4]:
import numpy as np
a=np.array([1,2,3])
print(a)
print(a.dtype)
print(a.shape)

[1 2 3]
int32
(3,)


# CREATE A 1-D ARRAY USING arange()

In [3]:
import numpy as np
a=np.arange(3)
print(a)
print(a.dtype)
print(a.shape)

[0 1 2]
int32
(3,)


# CREATE A 2-D ARRAY USING array()

In [5]:
import numpy as np
b=np.array(([1,2,3],[4,5,6]))
print(b)
print(a.dtype)
print(a.shape)

[[1 2 3]
 [4 5 6]]
int32
(3,)


# CREATE A 2-D ARRAY USING arange()

In [8]:
import numpy as np
b=np.arange(10).reshape(2,5) #if we multiply numbers in reshape() it must become 10
print(b)
print(b.dtype)
print(b.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
int32
(2, 5)


In [9]:
import numpy as np
b=np.arange(10).reshape(5,2)
print(b)
print(b.dtype)
print(b.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
int32
(5, 2)


# CREATE A 3-D ARRAY USING array()

In [12]:
import numpy as np
c=np.array(
    [
    [[1,2,3],[5,6,7]],         #3 2-d array with 2-rows and 3-columns
    [[8,9,10],[11,12,13]],
    [[14,15,16],[17,18,19]]
    ]
)
print(c)
print(c.dtype)
print(c.shape)

[[[ 1  2  3]
  [ 5  6  7]]

 [[ 8  9 10]
  [11 12 13]]

 [[14 15 16]
  [17 18 19]]]
int32
(3, 2, 3)


# CREATE A 3-D ARRAY USING arange()

In [18]:
import numpy as np
c=np.arange(1,19).reshape(3,3,2)  #3 2-d array with 3-rows and 2-columns
print(c)                          
print(a.dtype)
print(a.shape)      #shape() gives total number of elements in array

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]
int32
(3,)


# CREATE ARRAY OF ONES (1-D)

In [25]:
import numpy as np
d=np.ones(2,dtype=np.int32) #dtype of numpy is default float64
print(d)
print(d.dtype)
print(d.shape)

[1 1]
int32
(2,)


# CREATE ARRAY OF ONES(2-D)

In [27]:
import numpy as np
d=np.ones((2,3),dtype=np.int32)
print(d)
print(d.dtype)
print(d.shape)

[[1 1 1]
 [1 1 1]]
int32
(2, 3)


# CREATE ARRAY OF ONES(3-D)

In [30]:
import numpy as np
d=np.ones((3,2,3),dtype="int32")
print(d)
print(d.dtype)
print(d.shape)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
int32
(3, 2, 3)


# CREATE ARRAY OF ZEROS(1-D)

In [31]:
import numpy as np
f=np.zeros((3),dtype=np.int32)
print(f)
print(f.dtype)
print(f.shape)

[0 0 0]
int32
(3,)


# CREATE ARRAY OF ZEROS(2-D)

In [33]:
import numpy as np
f=np.zeros((2,3),dtype=np.int32)
print(f)
print(f.dtype)
print(f.shape)

[[0 0 0]
 [0 0 0]]
int32
(2, 3)


# CREATE ARRAY OF ZEROS(3-D)

In [36]:
import numpy as np
f=np.zeros((3,2,3),dtype=np.int32)
print(f)
print(f.dtype)
print(f.shape)

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
int32
(3, 2, 3)


# CREATE AN ARRAY WITH RANDOM NUMBERS(1-D)

In [38]:
import numpy as np
a=np.random.randint(1,6,size=(6))
print(a)
print(a.dtype)
print(a.shape)

[2 2 3 5 2 2]
int32
(6,)


# CREATE AN ARRAY WITH RANDOM NUMBERS(2-D)

In [39]:
import numpy as np
b=np.random.randint(1,11,size=(2,3))  #size==shape
print(b)
print(b.dtype)
print(b.shape)

[[10  9  3]
 [ 2  3  8]]
int32
(2, 3)


# CREATE AN ARRAY WITH RANDOM NUMBERS(3-D)

In [41]:
import numpy as np
c=np.random.randint(10,21,size=(3,2,3))
print(c)
print(c.dtype)
print(c.shape)

[[[15 17 17]
  [12 19 10]]

 [[14 19 16]
  [18 18 19]]

 [[19 12 12]
  [12 19 16]]]
int32
(3, 2, 3)


# CREATE ARRAY WITH SINGLE LOW MULTIPLE HIGH

In [43]:
import numpy as np
a=np.random.randint(5,[10,20,30])
print(a)
print(a.dtype)
print(a.shape)

[ 6  8 24]
int32
(3,)


# CREATE ARRAY WITH MULTIPLE LOW SINGLE HIGH

In [51]:
import numpy as np
b=np.random.randint([1,2,3],10)
print(b)
print(b.dtype)
print(b.shape)

[2 2 6]
int32
(3,)


# CREATE ARRAY WITH MULTIPLE LOW MULTIPLE HIGH

In [1]:
import numpy as np
a=np.random.randint([1,2,3,5],[10,20,30,40])
print(a)
print(a.dtype)
print(a.shape)

[ 7 11 12 39]
int32
(4,)


# CREATE ARRAY WITH RANDOM NUMBERS USING randn() (1-D)

In [4]:
import numpy as np
a=np.random.randn(5)
print(a)
print(a.dtype)
print(a.shape)

[-0.2967273  -0.77822052  0.42224473  0.16019949  0.80117945]
float64
(5,)


# CREATE NUMPY WITH RANDOM NUMBERS USING randn() (2-D)

In [8]:
import numpy as np
b=np.random.randn(3,2)
print(b)
print(b.dtype)
print(b.shape)

[[-0.23353583  0.02653656]
 [ 0.14683944 -0.22120399]
 [-0.18268175 -0.13126485]]
float64
(3, 2)


# CREATE ARRAY WITH RANDOM NUMBERS USING randn() (3-D)

In [2]:
import numpy as np
c=np.random.randn(3,3,2)
print(c)
print(c.dtype)
print(c.shape)

[[[ 0.38221224 -0.83933407]
  [-0.34879612 -0.58179621]
  [ 0.02546799  0.85191834]]

 [[-0.300013   -0.31905117]
  [-0.81584292 -0.95596324]
  [-0.81748045  1.71461078]]

 [[-0.07922627 -0.16872104]
  [-0.55225861  0.41403969]
  [ 0.68942813 -1.07592342]]]
float64
(3, 3, 2)


# CREATE ARRAY OF RANDOM NUMBERS USING rand()

In [6]:
import numpy as np
a=np.random.rand(5)
print(a)
print(a.dtype)
print(a.shape)

[0.87661673 0.27344438 0.36748383 0.45080365 0.18399461]
float64
(5,)


# POSITIVE INDEXING IN ARRAY(left - right)

In [1]:
#array with 1-D
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
print(arr[2])
print(arr[7])    #permanent method
arr[3]           #not permanent method

3
8


4

In [5]:
#array with 2-D
import numpy as np
arr=np.array([[1,2,3],[5,6,7],[8,9,10]])
print(arr[0,2])
print(arr[1,1])
print(arr[1,0])
print(arr[2,1])

3
6
5
9


In [6]:
#array with 3-D
import numpy as np
arr=np.array(
    [
        [[1,2,3],[4,5,6]],
        [[10,20,30],[12,13,14]],
        [[100,200,300],[400,500,600]]    
    ]
            )
print(arr[0,1,1])
print(arr[2,1,0])
print(arr[1,1,1])

5
400
13


# NEGETIVE INDEXING IN ARRAY(right - left)

In [17]:
#array with 1-D
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[-2])
print(arr[-1])
print(arr[-7])

6
7
1


In [7]:
#array with 2-D
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr[-1,-2])
print(arr[-2,-1])

5
3


In [21]:
#arry with 3-D
import numpy as np
arr=np.array(
    [
        [[1,2,3],[5,6,7]],
        [[12,13,14],[11,10,49]]
    ]
            )
print(arr[-1,-1,-3])
print(arr[-2,-1,-3])

11
5


# MIXING OF (+ AND -)

In [26]:
import numpy as np
arr=np.array(
    [
        [[2,3,4],[5,6,7]],
        [[10,2,4],[6,7,29]],
        [[22,11,14],[23,45,44]]
    ]
)
print(arr[1,1,1])
print(arr[-2,-1,-2])
print(arr[2,-1,2])
print(arr[-1,1,-2])

7
7
44
45


# NUMPY  ARRAY SLICING

slice elements from index 1 to index 5 from following array:

In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


slice elements from index 4 to the end of the array

In [9]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[4:])

[5 6 7 8 9]


slice elements from the beginning to index 4(not included)

In [7]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[:4])

[1 2 3 4]


# NEGETIVE SLICING

slice from the index 3 from the end to index 1 from the end:

In [10]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])
print(arr[-6:-2])

[5 6]
[2 3 4 5]


return every other elemrnt from index 1 to index 5

In [18]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


return every other element from the entire array

In [22]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


# SLICING 2-D ARRAYS

from the second element,slice elements from index 1 to index 4(not included)

In [13]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


from both arrays, return index 2:

In [19]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,2])

[3 8]


from both arrays,slice index 1 to index 4(not included),
this will return 2-d array 

In [24]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


# NUMPY ARRAY COPY VS VIEW

* The copy owns the data and any changes made to the copyed array it will not affect the original array, and any changes made to the original array will not affect the copied array.

* The view does not own the data and any changes made to the view will affect the original array and changes made to the original array will affect to the view 

In [25]:
import numpy as np
arr = np.array([1,2,3,4,5])
a = arr.copy()
print("original array")
print(arr)
print("affected array")
arr[2] = 10
print(arr)
print(a)

a[0] = 20
print("affected array")
print(a)

original array
[1 2 3 4 5]
affected array
[ 1  2 10  4  5]
[1 2 3 4 5]
affected array
[20  2  3  4  5]


In [11]:
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.view()
print("original array")
print(arr)
print("viewed array")
print(x)
print("affected array")
arr[0] = 30
print("arr : ",arr)
print(" x :",x)

original array
[1 2 3 4 5]
viewed array
[1 2 3 4 5]
affected array
arr :  [30  2  3  4  5]
 x : [30  2  3  4  5]


# reshape() FUNCTION

In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("original array :",arr) #1d

#2D ARRAY
b = arr.reshape(5,2) 
print("2D array with shape 5x2")
print(b)

c = arr.reshape(2,5) 
print("2D array with shape 2x5")
print(c)

#3D ARRAY 
d = arr.reshape(2,1,5)
print("3D array with shape 2,1,5")
print(d)

original array : [ 1  2  3  4  5  6  7  8  9 10]
2D array with shape 5x2
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
2D array with shape 2x5
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
3D array with shape 2,1,5
[[[ 1  2  3  4  5]]

 [[ 6  7  8  9 10]]]


# AGREEGATION FUNCTIONS

# sum() FUNCTION

In [23]:
import numpy as np
arr=np.array([1,2,3,4,5]) #1D
print("original 1D array : ",arr)
print(f"sum={np.sum(arr)}")
print()
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("original 2D array : ",arr1)
print(f"sum={np.sum(arr1)}")
print()
arr2=np.array(
              [
               [[1,2,3],[4,5,6]],
               [[10,20,30],[40,50,60]]    
              ]
             )
print("original 3D array : ",arr2)
print(f"sum={np.sum(arr2)}")

original 1D array :  [1 2 3 4 5]
sum=15

original 2D array :  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
sum=55

original 3D array :  [[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]
sum=231


In [29]:
#np.sum(array_name , axiws =0 or 1)
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("original array \n:",arr)

print("Across Rows") #column wise
print("sum =",np.sum(arr , axis=0))

print("Across Columns") #Row wise
print("sum =",np.sum(arr , axis=1))

original array 
: [[1 2 3 4]
 [5 6 7 8]]
Across Rows
sum = [ 6  8 10 12]
Across Columns
sum = [10 26]


# mean() FUNCTION

In [31]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
print("original array : ",arr)
print("mean : ",np.mean(arr)) 

original array :  [1 2 3 4 5 6 7 8]
mean :  4.5


In [31]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("original array \n: ",arr)

print("Across Rows") #column wise
print("Mean =",np.mean(arr , axis=0))

print("Across Columns") #Row wise
print("Mean =",np.mean(arr , axis=1))

original array 
:  [[1 2 3 4]
 [5 6 7 8]]
Across Rows
Mean = [3. 4. 5. 6.]
Across Columns
Mean = [2.5 6.5]


# std() FUNCTION

In [30]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("original array : ",arr)
print()
print("standard div : ",np.std(arr)) 

original array :  [[1 2 3 4]
 [5 6 7 8]]

standard div :  2.29128784747792


In [33]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("original array : ",arr)

print("Across Rows") #column wise
print("std div =",np.std(arr , axis=0))
print()
print("Across Columns") #Row wise
print("std div =",np.std(arr , axis=1))

original array :  [[1 2 3 4]
 [5 6 7 8]]
Across Rows
std div = [2. 2. 2. 2.]

Across Columns
std div = [1.11803399 1.11803399]


# var() FUNCTION

In [34]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("original array : ",arr)
print()
print("varients : ",np.var(arr)) 

original array :  [[1 2 3 4]
 [5 6 7 8]]

varients :  5.25


In [35]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("original array : ",arr)

print("Across Rows") #column wise
print("var =",np.var(arr , axis=0))
print()
print("Across Columns") #Row wise
print("var =",np.var(arr , axis=1))

original array :  [[1 2 3 4]
 [5 6 7 8]]
Across Rows
var = [4. 4. 4. 4.]

Across Columns
var = [1.25 1.25]


# min() FUNCTION

In [36]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("original array : ",arr)
print()
print("minimum : ",np.min(arr)) 

original array :  [[1 2 3 4]
 [5 6 7 8]]

minimum :  1


In [37]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("original array : ",arr)

print("Across Rows") #column wise
print("min =",np.min(arr , axis=0))
print()
print("Across Columns") #Row wise
print("min =",np.min(arr , axis=1))

original array :  [[1 2 3 4]
 [5 6 7 8]]
Across Rows
min = [1 2 3 4]

Across Columns
min = [1 5]


# max() FUNCTION

In [38]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("original array : ",arr)
print()
print("maximum : ",np.max(arr)) 

original array :  [[1 2 3 4]
 [5 6 7 8]]

maximum :  8


In [39]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("original array : ",arr)

print("Across Rows") #column wise
print("max =",np.max(arr , axis=0))
print()
print("Across Columns") #Row wise
print("max =",np.max(arr , axis=1))

original array :  [[1 2 3 4]
 [5 6 7 8]]
Across Rows
max = [5 6 7 8]

Across Columns
max = [4 8]
